services:
    postgres:
        image: postgres:17
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: calculateurped
            POSTGRES_USER: calculateurped
            POSTGRES_PASSWORD: secret
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata:
